" packer插件
lua require('plugins')
" 引入设置文件
source $HOME/.config/nvim/config/setting.vim
" 引入按键映射配置文件
source $HOME/.config/nvim/config/mapping.vim
" vim-airline
source ~/.config/nvim/themes/airline.vim
" 设置vim主题
source $HOME/.config/nvim/themes/gruvbox-material.vim
" 引入插件配置
source $HOME/.config/nvim/after/plugin/defx-icons.vim
