" 引入设置文件
source $HOME/.config/nvim/config/setting.vim
" 引入按键映射配置文件
source $HOME/.config/nvim/config/mapping.vim
" 插件配置文件
source $HOME/.config/nvim/config/plugins.vim
" vim-airline配置
source $HOME/.config/nvim/config/themes/airline.vim
" 设置vim主题
source $HOME/.config/nvim/config/themes/gruvbox-material.vim
